### ISSUE TITLE
Help with functionality

### ISSUE THREAD

**Issue by Bidou0418** [Viperize/BlockFreezer-PocketMine#1]
How do i add a block to the do not update list?
example required:
prevent flowing water and flowing lava?

as is i tried /bf a 9 world, /bf a 8.... and get 'Failed to add'

**Comment by ifvictr** [comment]
@Bidou0418 You have to do **/bf a 9 0 world**, not /bf a 9 world. Format is: /bf a [id] [metadeta] [world]. Same thing goes to /bf d.

**Comment by Bidou0418** [comment]
tried that too and tried again
still getting failed to add message.
my world is called New World so:
/bf a 9 0 New World= failed to add
or
/bf a 9 0 new world= failed to add

**Comment by Bidou0418** [comment]
@Gamecrafter

**Comment by ifvictr** [comment]
@Bidou0418 Why does your world name have a space in it?

**Comment by Bidou0418** [comment]
This is how my map was imported from mcpc (New World)
There are too many warps, signs and other custom plugins that use the New Worlds name for me to change it without causing major issues.
Are you saying the space is the proplem?
If so please fix for us. 
I am surely not the only one with a space in their world name.
let me know
Thanks for replying
(I have been trying to get some plugin dev's to fix stuff for months without any reply whatsoever)

**Comment by ifvictr** [comment]
@Bidou0418 You can manually add it the the world's data file (without using commands), go to **plugins/BlockFreezer/new world.txt** and add **<id>:<damage>**, each different block a a newline.

**Comment by Bidou0418** [comment]
thank you

**Comment by Bidou0418** [comment]
works well
