### ISSUE TITLE
suggestion 

### ISSUE THREAD

**Issue by Landy005** [Viperize/BlockFreezer-PocketMine#2]
We are a building server and we are very conceptional with our interior. Therefor we use alot of worldedit to make new interior designs. But is there a way or option to keep every block from blockupdating when breaking the block it is independed of or whenever u worldedited the block that it doesnt break on block update next to it? If not is there a way you might be able to implement it? We would be really thankfull to create easier interior this way. 

Thanks

**Comment by ifvictr** [comment]
@Landy005 What exactly are you talking about, I don't really understand you. Do you want an option that prevents **ALL** blocks from updating? If so, I can add that in a future update. If not, please reply with a clear description of what you want.

**Comment by Landy005** [comment]
Yes please would be awesome.

**Comment by Landy005** [comment]
http://imgur.com/a/Fiekz

Now for these designs we need to you use worldedit that's alot of work but if you could just do it by hand because there was no blockupdate at all that would be the best ;).

**Comment by Landy005** [comment]
There is a sort of bug where not all worlds are able to have blockfreezer even though i added the id's for that world. I know when you change from level.dat for a map it doesn't work anymore for that map.
